#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Kristene F.
description: Aspiring data enthusiast on a learning journey through the vast realm of analytics. With a marketing background and a flair for creative project management, I'm here to explore, experiment, and evolve. Join me in decoding the mysteries of data, one project at a time.
show_downloads: False
theme: jekyll-theme-minimal
